# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               eunchurn
tagline:             ''
description:         <center>eunchurn works archive<br> <img src="/public/eclogo.png" width=80></center>
url:                 https://eunchurn.com/
baseurl:             ''
representing_image: /public/images/7800413.jpeg

# About/contact
author:
  name:              eunchurn
  url:               https://twitter.com/eunchurn
  email:             eunchurn.park@gmail.com

# Custom vars
version:             1.0.0
github:
  repo: https://github.com/eunchurn
disqus:
  id: "eunchurn"
saram12saram: https://saram12saram.kr
researchgate: https://www.researchgate.net/profile/Eunchurn_Park/

# Plugins
plugins:
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-feed
paginate: 5
paginate_path: "page:num" 
markdown:    kramdown
g-analytics: UA-112690812-1
feed:
  path: atom.xml