# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               eunchurn
tagline:             'Blog'
description:         'work.'
url:                 https://eunchurn.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              eunchurn
  url:               https://twitter.com/eunchurn
  email:             eunchurn.park@gmail.com

# Custom vars
version:             1.0.0
