# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               eunchurn
tagline:             ''
description:         'works archive'
url:                 https://eunchurn.com/
baseurl:             ''
representing_image: /public/images/7800413.jpeg

# About/contact
author:
  name:              eunchurn
  url:               https://twitter.com/eunchurn
  email:             eunchurn.park@gmail.com

# Custom vars
version:             1.0.0
github:
  repo: https://github.com/eunchurn
disqus:
  id: "eunchurn"
saram12saram: https://saram12saram.kr

# Plugins
plugins:
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-feed
paginate: 5
paginate_path: "page:num" 
markdown:    kramdown
g-analytics: UA-112690812-1