# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               eunchurn
tagline:             ''
description:         'works archive $$ r_{B_{w,l,\phi}}(x,y) = \left(\prod_{i=1}^{\left| B_{w,l}\right|} s_{\rho_{i},\phi_{i}}(x,y)\right)^{1/\left|B_{w,l}\right|} $$'
url:                 https://eunchurn.com/
baseurl:             ''


# About/contact
author:
  name:              eunchurn
  url:               https://twitter.com/eunchurn
  email:             eunchurn.park@gmail.com

# Custom vars
version:             1.0.0
github:
  repo: https://github.com/eunchurn
disqus:
  id: "eunchurn"
saram12saram: https://saram12saram.kr

# Plugins
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num" 